### ISSUE TITLE
Makefile does not work on CentOS 6.6

### ISSUE THREAD

**Issue by allspace** [facebook/libphenom#75]
CentOS 6.6

steps:
download ck, build and install
download libphenom, run "configure", and then run "make"

result:
the make process run into a infinite loop. It does not stop until I press ctrl+c

**Comment by wez** [comment]
Can you include a paste of the build output?  If it loops forever it will be a big paste, so please just collect one loop of it (enough that we can see where it starts to repeat).

It's unlikely that the build is really looping, but perhaps more likely that you are using a networked filesystem and the clocks on your build host and on the system hosting the filesystem are out of sync, causing `make` to try to build it again.

**Comment by allspace** [comment]
Maybe you are right. I cannot reproduce this issue now. Please close it. Thanks.
