### ISSUE TITLE
i use redhat platfrom, need ck package

### ISSUE THREAD

**Issue by wuchuguang** [facebook/libphenom#76]
but i cant find ck package where can get it.

**Comment by wuchuguang** [comment]
checking for pkg-config... /usr/bin/pkg-config
Package ck was not found in the pkg-config search path.
Perhaps you should add the directory containing `ck.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ck' found
configure: error: ck is required

**Comment by wez** [comment]
Take a look at the requirements section of the docs for a list of dependencies and a link to Concurrency Kit:

http://facebook.github.io/libphenom/#README--System-Requirements

**Comment by sbahra** [comment]
Should be available in recent Fedora as well, going into RHEL soon
