### ISSUE TITLE
remove ph_stm_init prototype

### ISSUE THREAD

**Issue by tyrellj** [facebook/libphenom#77]
Looks like the ph_stm_init() prototype needs to be removed.

The function was replaced with stm_init/PH_LIBRARY_INIT_PRI, but the prototype was left behind.

**Comment by wez** [comment]
Good catch!  Would you like to submit a short PR to remove it?

**Comment by tyrellj** [comment]
This is my first pull-request, so please let me know if there's anything I should do or do differently. 

I also signed the CLA.

**Comment by wez** [comment]
Looks perfect; thanks!

**Comment by tyrellj** [comment]
Thank you
